# Generated by Django 4.0.5 on 2022-06-02 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=50)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('departure_airport', models.CharField(max_length=10)),
                ('arrival_airport', models.CharField(max_length=10)),
                ('departure_time', models.DateField()),
                ('arrival_time', models.DateField()),
                ('stops', models.IntegerField()),
                ('duration_mins', models.IntegerField()),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.airline')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.itinerary')),
            ],
        ),
    ]
